### ISSUE TITLE
No subAttributed in Parsed Schema

### ISSUE THREAD

**Issue by jeromedoucet** [xlgmokha/scim-kit#37]
**Describe the bug**
SubAttributes not parsed in Schema

**To Reproduce**
1. Create a Schema with a complex type inside (non empty `attributes` in it)
2. Serialize it 
3. Parse the resulting JSON
4. No subAttributes

**Expected behavior**
The parsed schema should include the subAttributes

I just fix it in a PR ;)

**Comment by xlgmokha** [comment]
Thanks @jeromedoucet for the explanation and fix! I will release a new version to rubygems.org soon.

**Comment by jeromedoucet** [comment]
@xlgmokha You're welcome ;)
