### ISSUE TITLE
Default error schema object in Scim::Kit::V2::Error is inaccurate

### ISSUE THREAD

**Issue by knguyendh** [xlgmokha/scim-kit#46]
https://github.com/xlgmokha/scim-kit/blob/0fd5824f940aac5bf924b7fa39fa5f01af473fbb/lib/scim/kit/v2/error.rb#L30

- `status` attribute should be of type string (see https://www.rfc-editor.org/rfc/rfc7644.html#section-3.12)
- `SCIM_TYPES` array has a duplicate `invalidSyntax` and is missing `invalidFilter`

Thanks a lot for this library, by the way. It's been very useful!

**Comment by xlgmokha** [comment]
Thanks for reporting this @knguyendh. 

[0.5.3](https://rubygems.org/gems/scim-kit/versions/0.5.3) has been released to Rubygems that includes fixes. Please take a look.
