### ISSUE TITLE
Need support for urn:ietf:params:scim:api:messages:2.0:PatchOp

### ISSUE THREAD

**Issue by knguyendh** [xlgmokha/scim-kit#55]
https://github.com/xlgmokha/scim-kit/blob/a7031f4204a4726187a127e80df7c1dd895c022d/lib/scim/kit/v2/messages.rb#L7

Hi again,

We are currently trying to support patch operations (https://www.rfc-editor.org/rfc/rfc7644#section-3.5.2), and it'd be nice to be able to recognize `urn:ietf:params:scim:api:messages:2.0:PatchOp` using your library.

Thanks a lot again for this library!

**Comment by xlgmokha** [comment]
Hey @knguyendh. Can you give me a little more information on the intended usage or how you would like scim-kit to support patch operations? Any example would be very helpful. 

Thank you for taking the time to write this issue.

**Comment by knguyendh** [comment]
It would just be cleaner to reference, for example, `Scim::Kit::V2::Messages::PATCH_OP` when validating that the patch request body coming in has a schemas array containing `urn:ietf:params:scim:api:messages:2.0:PatchOp`, instead of having to recreate the String or storing it in some global variable on our end which is what we're currently doing. Not too big of an issue though

**Comment by knguyendh** [comment]
Probably a separate issue, but I also noticed that if I define a `urn:ietf:params:scim:api:messages:2.0:PatchOp` schema with some required fields using the configuration object and then use the schema to create a `Scim::Kit::V2::Resource`, the `Scim::Kit::V2::Resource#valid?` method doesn't catch missing fields that are required, but it will catch missing fields that are required for our `User` and `Group` schemas

**Comment by knguyendh** [comment]
> Probably a separate issue, but I also noticed that if I define a `urn:ietf:params:scim:api:messages:2.0:PatchOp` schema with some required fields using the configuration object and then use the schema to create a `Scim::Kit::V2::Resource`, the `Scim::Kit::V2::Resource#valid?` method doesn't catch missing fields that are required, but it will catch missing fields that are required for our `User` and `Group` schemas. Although the patch request body schema is not really a `Resource`, we thought it'd be a clean way to validate the request body. Is this intentional behavior? If not, then probably something wrong on my end.

Nvm the reason `.valid?` doesn't work for a resource using PatchOp schema with attributes `schemas` and `Operations` is that the `"schemas"` attribute ends up setting The Resource object's instance variable `schemas` to a method that returns an empty array in the resource's method `schema_validations`

**Comment by xlgmokha** [comment]
I'm sorry for the delay @knguyendh. Do you mind taking a look at https://github.com/xlgmokha/scim-kit/pull/57 to see if this matches the desired outcome for this issue?

**Comment by knguyendh** [comment]
No problem about the delay. Looks good, just one concern on the PR

**Comment by knguyendh** [comment]
Thanks for doing this!
